name: Deploy to SprintHost

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/a1158424/domains/a1158424.xsph.ru/public_html/
